controllers/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from services.auth import AuthService
from services.recipe import RecipeService
from utils.forms import RegistrationForm, LoginForm, UpdateProfileForm, ChangePasswordForm
from flask_login import login_user, logout_user, current_user, login_required
from utils.decorators import guest_users_only

auth_bp = Blueprint('auth', __name__, url_prefix='/auth')

@auth_bp.route('/register', methods=['GET', 'POST'])
@guest_users_only
def register():
    form = RegistrationForm()
    page_css = [
        'css/forms.css'
    ]
    if form.validate_on_submit():
        name = form.username.data
        email = form.email.data
        password = form.password.data
        AuthService.register_user(name, email, password)
        flash('Account created successfully', 'success')
        return redirect(url_for('auth.login'))
    elif form.errors.items():
        flash('Please correct the form errors and try again.', 'error')

    return render_template('auth/register.html', form=form, page_css = page_css, active_m='regiseter')


@auth_bp.route('/login', methods=['GET', 'POST'])
@guest_users_only
def login():
    # guest_users_only()
    page_css = [
        'css/forms.css'
    ]
    form = LoginForm()

    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data

        user = AuthService.get_user_by_email(email)

        if user and AuthService.verify_password(user, password):
            login_user(user)
            flash('Logged in successfully', 'success')
            next = request.args.get('next')
            return redirect(next or url_for('pages.home'))
        else:
            flash('Invalid email or password', 'error')

    return render_template('auth/login.html', form=form, page_css = page_css, active_m='login')

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logged out successfully', 'success')
    return redirect(url_for('auth.login'))

@auth_bp.route('/profile')
@login_required
def profile():
    page_css = [
        'css/profile.css'
    ]
    c_user = current_user

    per_page = RecipeService.per_page
    page = request.args.get('page', 1, type=int)

    recipes = RecipeService().get_user_created_recipes(current_user.id, page)
    total_count = recipes.total
    next = recipes.next_num if recipes.has_next else None
    prev = recipes.prev_num if recipes.has_prev else None

    # Calculate the range of records being displayed
    start_index = (page - 1) * per_page + 1
    end_index = min(start_index + per_page - 1, total_count)
    showing = f"{start_index} - {end_index} of {total_count} recipes."

    return render_template(
        'auth/profile.html'
        ,search_results=recipes.items
        , user = c_user
        , showing=showing
        , next = next
        , prev = prev
        , page_css = page_css
    )



@auth_bp.route('/update_profile', methods=['GET', 'POST'])
@login_required
def update_profile():
    form = UpdateProfileForm()
    user = current_user
    page_css = [
        'css/forms.css'
    ]
    if form.validate_on_submit():
        name = form.username.data
        email = form.email.data
        user = AuthService.update_profile(user, name, email)
        flash('Account Updated successfully', 'success')
        return redirect(url_for('auth.profile'))
    elif form.errors.items():
        flash('Please correct the form errors and try again.', 'error')
    else:
        form.init_prfile()
    return render_template('auth/update_profile.html', form = form, page_css = page_css)

@auth_bp.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm()
    user = current_user
    page_css = [
        'css/forms.css'
    ]
    if form.validate_on_submit():
        password = form.new_password.data
        user = AuthService.change_password(user, password)
        flash('Password changed successfully', 'success')
        return redirect(url_for('auth.profile'))
    elif form.errors.items():
        flash('Please correct the form errors and try again.', 'error')
    return render_template('auth/change_password.html', form = form, page_css = page_css)

controllers/pages.py
"""
This file defines the routes for the Flask application. It contains handlers for rendering HTML templates and handling user requests.

Functions:
    home(): Renders the home page of the website.
    search(): Renders the search results page based on the user's query.
    healthy(): Renders the listing page for the "Healthy" recipe category.
    vegetarian(): Renders the listing page for the "Vegetarian" recipe category.
    baking(): Renders the listing page for the "Baking" recipe category.
    miscellaneous(): Renders the listing page for the "Miscellaneous" recipe category.
    category_listing(category, showing): Renders the listing page for a given recipe category.
"""

from flask import Blueprint, render_template, request, flash, redirect, url_for
from services.auth import AuthService
from utils.forms import RegistrationForm, LoginForm
from flask_login import login_user, logout_user, current_user
from models.recipe_category import RecipeCategory
from models.recipe import Recipe
from services.recipe import RecipeService
from models.user import User
from database import or_, and_

pages_bp = Blueprint('pages', __name__,)


@pages_bp.route('/', methods=['GET'])
def home():
    r_service = RecipeService()
    ja_recipes = r_service.get_latest_banner_recipes()
    categories = ["Healthy", "Vegitarian", "Baking"]
    cat_reipes = list(map(lambda c: r_service.get_latest_banner_cat_recipes(c), categories))
    page_js = [
        'scripts/slider.js'
    ]
    categories = r_service.get_all_categories()
    return render_template(
        'pages/home.html'
        , ja_recipes=ja_recipes
        , categories=categories
        , h_recipes=cat_reipes[0]
        , v_recipes = cat_reipes[1]
        , b_recipes = cat_reipes[2]
        , page_js = page_js
    )


@pages_bp.route('/healthy', methods=['GET'])
def healthy():
    showing = '''Explore a wide range of nutritious and delicious healthy recipes with our pagination feature. 
                Start with the first {}-{} out of {} recipes and browse at your leisure.'''
    category = "Healthy"
    return category_listing(category, showing)

@pages_bp.route('/vegitarian', methods=['GET'])
def vegitarian():
    showing = '''Explore a wide range of delicious and healthy vegetarian recipes with our pagination feature. 
                Start with the first {}-{} out of {} recipes and discover new flavors at your leisure.'''
    category = "Vegitarian"
    return category_listing(category, showing)

@pages_bp.route('/baking', methods=['GET'])
def baking():
    showing = '''Indulge your sweet tooth with our collection of delicious and easy-to-follow baking recipes. 
                Start with the first {}-{} out of {} recipes and bake up a storm at your own pace.'''
    category = "Baking"
    return category_listing(category, showing)

@pages_bp.route('/miscellaneous', methods=['GET'])
def miscellaneous():
    showing = '''Explore a diverse selection of mouth-watering recipes from our miscellaneous category. 
    Start with the first {}-{} out of {} recipes and discover new favorites at your own pace.'''
    category = "Miscellaneous"
    return category_listing(category, showing)

@pages_bp.route('/about', methods=['GET'])
def about():
    page_css = [
        'css/about.css'
    ]
    return render_template(
        'pages/about.html'
        ,page_css = page_css
    )

def category_listing(category, showing):
    
    per_page = RecipeService.per_page
    # Get the current page number from the URL parameter or default to the first page
    page = request.args.get('page', 1, type=int)
    
    recipes =  RecipeService().get_category_listing_recipes(category, page)
    total_count = recipes.total
    next = recipes.next_num if recipes.has_next else None
    prev = recipes.prev_num if recipes.has_prev else None

    # Calculate the range of records being displayed
    start_index = (page - 1) * per_page + 1
    end_index = min(start_index + per_page - 1, total_count)

    # Replace any placeholders in the 'showing' message with the actual values
    showing = showing.format(start_index, end_index, total_count)

    # Render the category listing HTML template and pass in the search results, pagination metadata, and category title
    return render_template(
        'pages/category_listing.html',
        search_results=recipes.items,
        showing=showing,
        next=next,
        prev=prev,
        title=category
    )

templates/base_n.html
{% from "element_helpers.html" import render_link %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Yummy Recipes</title>
    <link rel="icon" href="{{ url_for('static', filename='images/site/favicon.ico') }}" type="image/x-icon">
    <!-- include css files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/base.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/slider.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/recipes_containers.css') }}">
    {% if page_css %}
        {% for css in page_css %}
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename=css) }}">
        {% endfor %}
    {% endif %}
    <!-- include js files -->
    <script src="{{ url_for('static', filename='scripts/menue.js') }}"></script>
    {% if page_js %}
        {% for js in page_js %}
        <script src="{{ url_for('static', filename=js) }}"></script>
        {% endfor %}
    {% endif %}
</head>

<body>
    <!-- main wrapper to set the site area -->
    <div class="main">
        <!-- header section to load navigations and log -->
        <div class="header">
            <!-- top most navigation bar -->
            <div class="global-header">
                <ul>
                {% if current_user.is_authenticated %}
                    <li> {{render_link(url_for('auth.profile'), 'Profile', '', '/auth/profile')}}</li>
                    <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                {% else %}
                    <li> {{render_link(url_for('auth.register'), 'Register', '', '/auth/register')}}</li>
                    <li>{{render_link(url_for('auth.login'), 'Lgoin', '', '/auth/login')}}</li>
                {% endif %}
                </ul>
            </div>
            <!-- top most navigation bar end -->

            <!-- header contents including logo and search bar -->
            <div class="content">
                <!-- logo image -->
                <div class="logo">
                    <a href="/"><img src="{{ url_for('static', filename='images/site/logo.jpg') }}" /></a>
                </div>
                <!-- search block visible in desktop -->
                <div class="cont-search_wrapper">
                    {% include 'snippets/search_snippet.html'  %}
                </div>
                <!-- wrapper for icons to display in mobile devices -->
                <div class="mob-header-icons">
                    <!-- hamburger menue button visible in mobile devices (phons and tabs) -->
                    <a href="javascript:void(0);" class="icon" onclick="navbarToggle()">
                        <div class="hamburger">
                            <span class="line"></span>
                            <span class="line"></span>
                            <span class="line"></span>
                        </div>
                    </a>
                    <!-- search button icon for phones -->
                    <a href="javascript:void(0);" class="icon" onclick="searchbarToggle()">
                        <div class="search-icon"><img src="{{ url_for('static', filename='images/site/search.jpg') }}"/></div>
                    </a>
                    
                </div>
                
            </div>
            <!-- header contents including logo and search bar end -->

            <!-- main navigation bar -->
            <div class="topnav" id="myTopnav">
                {{render_link(url_for('pages.home'), 'Home', '', '/')}}
                {{render_link(url_for('pages.healthy'), 'Healthy', '', '/healthy')}}
                {{render_link(url_for('pages.vegitarian'), 'Vegitatian', '', '/vegitarian')}}
                {{render_link(url_for('pages.baking'), 'Baking', '', '/baking')}}
                {{render_link(url_for('pages.miscellaneous'), 'Miscellaneous', '', '/miscellaneous')}}
                {{render_link(url_for('pages.about'), 'About', '', '/about')}}
                
                <!-- <a href="#about">Create</a> -->
            </div>
            <!-- search box for mobile devices -->
            
            <!-- search block visible in desktop -->
            <div class="mob-search-wrapper" id="mobSearchBox">
                <div class="cont-search_wrapper">
                    {% include 'snippets/search_snippet.html'  %}
                </div>
            </div>
        </div>
        <!-- section to load page contents -->
        <div class="page-container">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                    {{ message }}
                    </div>
                {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
        <!-- section to load page contents end -->
        <div class="footer-placeholder"></div>
        <div class="footer">
            <p>Find the perfect recipe for any occasion with our recipe search. Discover new flavors and cuisines today.</p>
        </div>
    </div>


</body>

</html>

templates/element_helpers.html
<!-- this macro is created to append active class into the links to centralize the logic -->
{% macro render_link(link, label, classes, active_path) %}
    <a href="{{ link }}" class="{{ classes }}{% if request.path == active_path %} active{% endif %}">{{ label }}</a>
{% endmacro %}

templates/form_helpers.html
{% macro render_field(field) %}
<div class="form-group {{ 'form-group-error' if field.errors else '' }}">
  <dt>{{ field.label }}</dt>
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
  {% for error in field.errors %}
    <span>{{ error }}</span>
  {% endfor %}
  {% endif %}
  </dd>
</div>
{% endmacro %}  


{% macro render_field_list(field_list, lable, delete_function) %}
<div class = "field-list" >
  <div class="form-group-lable"> {{lable}}</div>
  <div class="form-group-wrapper">
    {%for field in field_list%}
      <div class="form-group {{ 'form-group-error' if field.errors else '' }}">
        <dt>{{ field.label }}</dt>
        <dd>{{ field(**kwargs)|safe }}
        {% if field.errors %}
        {% for error in field.errors %}
          <span>{{ error }}</span>
        {% endfor %}
        {% endif %}
        </dd>
      </div>
    {%endfor%}
  </div>
  <div class="form-group-action delete-f-group-item"> <a href="#" onclick="{{delete_function}}(this)"> Delete </a></div>
</div>
{% endmacro %}  