models/recipe.py
import datetime
from database import db, Model, session, Column, Boolean, Integer, String, DateTime, ForeignKey, relationship, Text
from flask_login import UserMixin

class Recipe(Model, UserMixin):
    id = Column(Integer, primary_key=True, autoincrement=True)
    title = Column(String(50))
    description = Column(Text)
    image = Column(String(50), unique=True)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow)
    ingredients = relationship('Ingredients', backref='recipe', lazy=True)
    methods = relationship('Methods', backref='recipe', lazy=True)
    recipe_category_id = Column(Integer, ForeignKey('recipe_category.id'), nullable=False)
    user_id = Column(Integer, ForeignKey('user.id'), nullable=False)

    def save(self):
        session.add(self)
        session.commit()
    

controllers/recipes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from services.auth import AuthService
from services.recipe import RecipeService
from utils.forms import RecipeCreateForm, MethodForm, IngredientForm
from flask_login import login_user, logout_user, current_user, login_required
from utils.decorators import guest_users_only

recipes_bp = Blueprint('recipes', __name__, url_prefix='/recipes')

@recipes_bp.route('/', methods=['GET', 'POST'])
@login_required
def index():
    per_page = RecipeService.per_page
    page = request.args.get('page', 1, type=int)

    recipes = RecipeService().get_user_created_recipes(current_user.id, page)
    total_count = recipes.total
    next = recipes.next_num if recipes.has_next else None
    prev = recipes.prev_num if recipes.has_prev else None

    # Calculate the range of records being displayed
    start_index = (page - 1) * per_page + 1
    end_index = min(start_index + per_page - 1, total_count)
    showing = f"{start_index} - {end_index} of {total_count} recipes."

    return render_template(
        'recipes/user_recipes.html'
        , search_results=recipes.items
        , showing=showing
        , next = next
        , prev = prev
    )

@recipes_bp.route('/search', methods=['GET'])
def search():
    per_page = RecipeService.per_page
    search_query = request.args.get('q')
    page = request.args.get('page', 1, type=int)
    recipes = RecipeService().search_recipes(search_query, page)
    total_count = recipes.total
    next = recipes.next_num if recipes.has_next else None
    prev = recipes.prev_num if recipes.has_prev else None

    # Calculate the range of records being displayed
    start_index = (page - 1) * per_page + 1
    end_index = min(start_index + per_page - 1, total_count)
    showing = f"{start_index} - {end_index} of {total_count} recipes for \"{search_query}\""
    
    return render_template(
        'recipes/search_results.html'
        , search_results=recipes.items
        , showing=showing
        , next = next
        , prev = prev
        , q = search_query
        ,current_user_id =  current_user.id if current_user.is_authenticated else None
    )

@recipes_bp.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = RecipeCreateForm()
    form.init_form()
    user = current_user
    page_css = [
        'css/forms.css'
    ]
    page_js = [
        '/scripts/recipes_forms.js'
    ]
    if form.validate_on_submit():
        recipe_service = RecipeService()
        title = form.title.data
        recipe_params = {
            'title': title,
            'file_name': form.recipe_image_name,
            'description': form.description.data,
            'category': form.category.data,
            'user_id': user.id
        }

        ingredients = []
        for ingredient in form.ingredients.entries:
            ingredient_form = ingredient.form
            if isinstance(ingredient_form, IngredientForm):
                ingredient_data = {
                    'name': ingredient_form.name.data,
                    'qty': ingredient_form.quantity.data,
                    'unit': ingredient_form.unit.data
                }
                ingredients.append(ingredient_data)

        method_steps = []
        for method in form.methods.entries:
            method_form = method.form
            if isinstance(method_form, MethodForm):
                method_data = {
                    'title': method_form.title.data
                    , 'discription': method_form.discription.data
                }
                method_steps.append(method_data)
            
        

        new_recipe = recipe_service.create_recipe(recipe_params, ingredients,  method_steps)
        flash('Account Updated successfully', 'success')
        return redirect(url_for('recipes.index'))

    elif form.errors.items():
        flash('Please correct the form errors and try again.', 'error')
    return render_template('recipes/create_recipe.html', form = form, page_css = page_css, page_js = page_js)

@recipes_bp.route('/<int:recipe_id>')
def get_recipe(recipe_id):
    # Endpoint function to load recipe details page

    recipe = RecipeService().get_recipe_bu_id(recipe_id)
    page_css = [
        'css/recipe_details.css'
    ]
    return render_template('recipes/details.html', recipe=recipe, page_css = page_css)
    

templates/recipes/create_recipe.html
{% from "form_helpers.html" import render_field, render_field_list %}
{% extends 'base_n.html' %}

{% block content %}
<div class="content middle_container">
  {% include 'snippets/profile_back_link.html' %}
  <h2>Create Recipe</h2>
  <form method="POST" enctype="multipart/form-data">
    {{ form.csrf_token }}
    {{ render_field(form.category) }}
    {{ render_field(form.title) }}
    {{ render_field(form.recipe_image) }}
    {{ render_field(form.description) }}
    <div class="ingradiants-group form-list-group">
        {%for i in form.ingredients %}
        {{ render_field_list(i, "Ingredient " + loop.index|string, "delete_ingradient" ) }}
        {%endfor%}
        <div class="add-ingradient add-f-group-item"> <a href="#" onclick="add_ingradient(this)">Add Ingredient</a></div>
    </div>

    <div class="method-group form-list-group" >
        {%for i in form.methods %}
        {{ render_field_list(i, "Method, Step " + loop.index|string, "delete_step") }}
        {%endfor%}
        <div class="add-ingradient add-f-group-item"> <a href="#" onclick="add_method(this)">Add Step</a></div>
    </div>

    <div class="action-button">
      <button type="reset"  class="reset">Cancel</button>
      <button type="submit" class="submit">Create</button>
    </div>
    
  </form>
</div>
{% endblock %}

templates/recipes/details.html
{% from "form_helpers.html" import render_field %}
{% extends 'base_n.html' %}

{% block content %}
<div class="content middle_container">
  <h1>{{recipe.title}}</h1>
  <div class="description">{{recipe.description}}</div>
  <div class="details-recipe-image"><img src="{{ url_for('static', filename= 'images/uploads/dishes/' + recipe.image) }}"/></div>
  {%if recipe.ingredients %}
    <div class="group-container">
        <div class="group-lable"><h3>Ingredients</h3></div>
        <ul>
            {%for i in recipe.ingredients %}
                <li>{{i.quantity}}{{i.unit}} {{i.name}}</li>
            {%endfor%}
        </ul>
    </div>
  {%endif%}
  {%if recipe.methods %}
    <div class="group-container">
        <div class="group-lable"><h3>Method</h3></div>
        <ol>
            {%for m in recipe.methods %}
                <li> 
                    {% if m.title %} <h4>{{m.title}}</h4> {%endif%}
                    <p>{{m.discription}}</p>
                </li>
            {%endfor%}
        </ol>
    </div>
  {%endif%}
  <div class="page-end"></div>
</div>
{% endblock %}

templates/recipes/search_results.html
{% from "form_helpers.html" import render_field %}
{% extends 'base_n.html' %}

{% block content %}
<div class="content middle_container">
  <h1>Search Results</h1>
  <p>{{showing}}</p>
  {% if  search_results:%}
        <div class="healthy-space middle_container recipe-banners" >
            <div class="recipe-container">
                {% for recipe in search_results %}
                    {% set action = False %}
                    {% set id=recipe.id%}
                    {% set title=recipe.title + " ~by " + recipe.user.name%}
                    {% set img= url_for('static', filename= "images/uploads/dishes/" + recipe.image)%}
                    {% if current_user_id == recipe.user.id %}
                    {% set action = True %}    
                    {% set id = recipe.id %}   
                    {% endif%}
                    {% include 'snippets/recipe_card.html' %}
                {% endfor %}
            </div>
            <p class="pagination">
                {% if prev %}
                    <a class="prev" href="{{ url_for(request.endpoint, q=q, page=prev) }}">Prev</a>
                {% endif %}
                {% if next %}
                    <a class="next" href="{{ url_for(request.endpoint, q=q, page=next) }}">Next</a>
                {% endif %}
            </p>
            
        </div>
        
    {% endif %}
</div>
{% endblock %}

templates/recipes/user_recipes.html
{% from "form_helpers.html" import render_field %}
{% extends 'base_n.html' %}

{% block content %}
<div class="content middle_container">
  <div class="create-recipe"><a href="{{url_for('recipes.create')}}">Create</a></div>
  <h1>Your own recipes</h1>
  <p>{{showing}}</p>
  {% if  search_results:%}
        <div class="middle_container recipe-banners" >
            <div class="recipe-container">
                {% for recipe in search_results %}
                    {% set title=recipe.title %}
                    {% set img= url_for('static', filename= "images/uploads/dishes/" + recipe.image)%}
                    {% set id = recipe.id %}
                    {% set action = True %}
                    {% include 'snippets/recipe_card.html' %}
                {% endfor %}
            </div>
        </div>
        <p class="pagination">
            {% if prev %}
                <a class="prev" href="{{ url_for(request.endpoint, q=q, page=prev) }}">Prev</a>
            {% endif %}
            {% if next %}
                <a class="next" href="{{ url_for(request.endpoint, page=next) }}">Next</a>
            {% endif %}
        </p>
    {% endif %}
</div>
{% endblock %}